name: Build

on:
  push:

jobs:

  tagger:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Derive correct Tag
        id: derive_tag_name
        run: |
          if [ $GITHUB_REF_NAME == "master" ]; then
            echo "::set-output name=tag_name::v0.0.0"
          else 
            echo "::set-output name=tag_name::$GITHUB_REF_NAME"
          fi
      - run: echo "::set-output name=test123::asdasd"

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [ tagger ]
    steps:
      - name: Dump context
        env:
          CONTEXT: ${{ toJSON(needs) }}
        run: echo "$CONTEXT"
