name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Build AskSinAnalyzerXS
        run: |
          (cd ui && npm ci && npm run build)
          (cd app && npm ci && npm run tsc)
          (cd app && node scripts/make-node-pkg.js)

      - name: Build/release Electron Apps
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
