name: Update v0.0.0

on:
  push:
    branches:
      - master

jobs:
  update_tag:
      name: Update dev tag
      runs-on: ubuntu-latest
      steps:
        - name: Check out Git repository
          uses: actions/checkout@v2
        - name: Update tag
          run: |
            export OWNER=$(echo $GITHUB_REPOSITORY | cut -d/ -f1)
            git config --global user.name 'Github Action'
            git config --global user.email $OWNER@users.noreply.github.com
            git tag -f v0.0.0
            git push -f origin v0.0.0
